### ISSUE TITLE
Catch joining errors early from CMD 17, fails in CMD 45

### ISSUE THREAD

**Issue by petershaw** [data-derp/exercise-ev-databricks#19]
Tests are working all the way down to e2e tests and fail then if there is a little mistake in a command all the way up. 

That is really hart to catch, because the unit-tests are working fine.

When someone messed up CMD 17 (join_with_start_transaction_responses) and join the input_df into join_df, than there is en error in CMD 45. 
```
AssertionError: Expected [2.17, 1.58, 1.0], but got [2.17, 1.58, 1.25]
```

Correct solution for 17 is: 
```python
        return input_df. \
        join(join_df, input_df.transaction_id == join_df.transaction_id, "left"). \
        select(
            join_df.charge_point_id, 
            join_df.transaction_id, 
            join_df.meter_start, 
            input_df.meter_stop.alias("meter_stop"), 
            join_df.start_timestamp, 
            input_df.timestamp.alias("stop_timestamp")
        )
```

Wrong solution example is
```python
        return join_df. \
            join(input_df, join_df.transaction_id == input_df.transaction_id, "left"). \
            select(
                join_df.charge_point_id, 
                join_df.transaction_id, 
                join_df.meter_start, 
                input_df.meter_stop, 
                join_df.start_timestamp, 
                input_df.timestamp.alias("stop_timestamp")
            )
```
when change "left"-join to "right"-join all is working fine. 

If the wrong way changes the data (besides the order), then this should be tested early, because there is no way to find the error later on.

**Comment by kelseymok** [comment]
Interesting - I need to see what the actual correct value is. Will investigate.

**Comment by syed-tw** [comment]
yes..thats correct @kelseymok

**Comment by kelseymok** [comment]
https://github.com/data-derp/exercise_ev_databricks_unit_tests/commit/c2d21bb2ac44b9d8c2266df629e67181a30c9169

**Comment by kelseymok** [comment]
I think this resolves: https://github.com/data-derp/exercise-ev-databricks/issues/24
